[book]
authors = ["Julia Benisty", "Clement Delafargue", "Geoffroy Couprie"]
language = "en"
multilingual = false
src = "src"
title = "Eclipse Biscuit"

[output.html]
git-repository-url = "https://github.com/eclipse-biscuit/biscuit"
git-repository-icon = "fa-github"

[output.html.playground]
runnable = false

